### ISSUE TITLE
bug with fix

### ISSUE THREAD

**Issue by pkoppstein** [joelpurra/jq-bigint#1]
Towards the end of  the definition of `long_add(num1; num2)` the occurrence of "negate" in the following line is incorrect:

```
    else minus($a2[1] ;$a1[1]) | negate
```

After correcting the spacing around the semicolon, the line should read:

```
minus($a2[1]; $a1[1])
```

Relevant test case: long_add("-2"; "1")

The bug has been fixed at https://gist.github.com/pkoppstein/d06a123f30c033195841

**Comment by joelpurra** [comment]
@pkoppstein: I'm on the road, so gave you collaborator status to implement the patch =)

**Comment by pkoppstein** [comment]
f0c078be49f8a21fafd697984169e94e8f906789

**Comment by joelpurra** [comment]
@pkoppstein: great, thanks! Would you mind adding your test to the other test cases though?

**Comment by pkoppstein** [comment]
@joelpurra:  The current version of BigInt.jq was used to compute `range(0;61) | Bernoulli(.)` (see http://rosettacode.org/wiki/Bernoulli_numbers#jq).  It might be worthwhile adding tests for, say, range(0;20), but I'm not sure how to do that.

**Comment by joelpurra** [comment]
@pkoppstein: noticed that you added relevant tests too - thanks!

Larger (multiple lines of code, lots of input or output) aren't suitable for the four-line test format. For larger (and "real world usage") test cases it's actually easier to `jqnpm generate` a new package like `jq-bernoulli`, import `jq-bigint`, write the Bernoulli code and enter tests there. This also means reusability for little more than the cost of writing tests =)
